function out1 = quadB(Ix,Iy,Iz,m,phi,psi,theta)
%QUADB
%    OUT1 = QUADB(IX,IY,IZ,M,PHI,PSI,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    12-Jan-2017 18:01:30

t2 = 1.0./m;
t3 = cos(psi);
t4 = sin(phi);
t5 = cos(phi);
t6 = sin(psi);
t7 = sin(theta);
out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t2.*(t4.*t6+t3.*t5.*t7),-t2.*(t3.*t4-t5.*t6.*t7),t2.*t5.*cos(theta),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./Ix,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./Iy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./Iz],[12,4]);
